param([int]$Count = 180)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Net.Http

$repoRoot = Split-Path -Parent $PSScriptRoot
$assetDir = Join-Path $repoRoot 'packages/client/public/memes'
$sharedDir = Join-Path $repoRoot 'packages/shared/src/games/memes'
$client = [System.Net.Http.HttpClient]::new()
$client.Timeout = [TimeSpan]::FromSeconds(30)
$client.DefaultRequestHeaders.UserAgent.ParseAdd('Mozilla/5.0 HasalonGames/1.0 (family game asset curation)')

$cards = [System.Collections.Generic.List[object]]::new()
$seen = [System.Collections.Generic.HashSet[string]]::new()
$pattern = '<div class="mt-box">.*?href="/memetemplate/(\d+)/([^"]+)"[^>]*>(.*?)</a>.*?<img[^>]+src="//i\.imgflip\.com/2/([^".]+)\.jpg"'
for ($page = 1; $cards.Count -lt $Count; $page += 1) {
  $html = $client.GetStringAsync("https://imgflip.com/gif-templates?page=$page").GetAwaiter().GetResult()
  foreach ($match in [regex]::Matches($html, $pattern, [System.Text.RegularExpressions.RegexOptions]::Singleline)) {
    $numericId = $match.Groups[1].Value
    if (-not $seen.Add($numericId)) { continue }
    $cards.Add([pscustomobject]@{
      numericId = $numericId
      slug = $match.Groups[2].Value
      name = [System.Net.WebUtility]::HtmlDecode(([regex]::Replace($match.Groups[3].Value, '<[^>]+>', '')).Trim())
      code = $match.Groups[4].Value
    })
    if ($cards.Count -ge $Count) { break }
  }
  # Pages are 40 items; scale the ceiling with the count plus four spare rather
  # than fixing it at the eight a run of 80 happened to need.
  if ($page -gt ([Math]::Ceiling($Count / 40.0) + 4)) {
    throw "Imgflip returned only $($cards.Count) animated templates, need $Count."
  }
}

$items = [System.Collections.Generic.List[object]]::new()
foreach ($card in $cards) {
  $id = "gif-$($card.numericId)-$($card.slug.ToLowerInvariant())"
  $source = "https://imgflip.com/gif-maker/$($card.numericId)/$($card.slug)"
  $detail = $client.GetStringAsync($source).GetAwaiter().GetResult()
  $dimensions = [regex]::Match($detail, 'gif_template=\{[^;]*?"w":"(\d+)","h":"(\d+)"')
  if (-not $dimensions.Success) { throw "Could not read dimensions for $($card.name)." }
  $width = [int]$dimensions.Groups[1].Value
  $height = [int]$dimensions.Groups[2].Value
  $mediaUrl = "https://i.imgflip.com/$($card.code).mp4"
  $target = Join-Path $assetDir "$id.mp4"
  $bytes = $client.GetByteArrayAsync($mediaUrl).GetAwaiter().GetResult()
  [System.IO.File]::WriteAllBytes($target, $bytes)
  $items.Add([pscustomobject]@{
    id = $id
    name = $card.name
    aspect = [Math]::Round($width / $height, 6)
    source = $source
  })
  Write-Output ("[{0}/{1}] {2} ({3:N0} KB)" -f $items.Count, $Count, $card.name, ($bytes.Length / 1KB))
}

$generated = [System.Collections.Generic.List[string]]::new()
$generated.Add('/** Generated by scripts/curate-gif-memes.ps1 from Imgflip''s live GIF ranking. */')
$generated.Add('import type { MemeAsset } from ''./templateAssets'';')
$generated.Add('export const GIF_MEME_ASSETS: MemeAsset[] = [')
foreach ($item in $items) {
  $escapedName = ([string]$item.name).Replace('\', '\\').Replace("'", "\'")
  $generated.Add("  { id: '$($item.id)', name: '$escapedName', aspect: $($item.aspect), slots: 2, tier: 'reaction', source: '$($item.source)', format: 'mp4' },")
}
$generated.Add('];')
[System.IO.File]::WriteAllLines((Join-Path $sharedDir 'gifTemplateAssets.ts'), $generated, [System.Text.UTF8Encoding]::new($false))

$attributionPath = Join-Path $assetDir 'ATTRIBUTION.md'
$attribution = [System.Collections.Generic.List[string]]::new()
$existing = [System.IO.File]::ReadAllText($attributionPath)
$marker = "`n## Animated GIF templates"
$markerAt = $existing.IndexOf($marker)
if ($markerAt -ge 0) { $existing = $existing.Substring(0, $markerAt) }
$attribution.Add($existing.TrimEnd())
$attribution.Add('')
$attribution.Add('## Animated GIF templates')
$attribution.Add('')
$attribution.Add('Downloaded as compact, muted MP4 loops from Imgflip''s live GIF Templates ranking. They are presented as animated GIF memes in the game while avoiding the much larger legacy GIF encoding.')
$attribution.Add('')
$attribution.Add('| rank | id | template | source |')
$attribution.Add('|---:|---|---|---|')
for ($index = 0; $index -lt $items.Count; $index += 1) {
  $item = $items[$index]
  $name = ([string]$item.name).Replace('|', '\|')
  $attribution.Add("| $($index + 1) | ``$($item.id)`` | $name | [Imgflip GIF template]($($item.source)) |")
}
[System.IO.File]::WriteAllLines($attributionPath, $attribution, [System.Text.UTF8Encoding]::new($false))
Write-Output "Wrote $($items.Count) current Imgflip animated templates."
